baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Davi Augusto'
theme = 'cli-portfolio'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false
pagination.pagerSize = 5

[languages]
[languages.en]
languageName = 'English'
weight = 1
contentDir = 'content'
[languages.pt]
languageName = 'Português'
weight = 2
contentDir = 'content/pt'
languageCode = 'pt-br'

[params]
github = "https://github.com/agstrc"
email = "davi ＠ agst ⋅ dev"
opengraphDescription = "Davi Augusto - Software developer"
